### ISSUE TITLE
Ambush + Gambling Chip crashes the game

### ISSUE THREAD

**Issue by Vurttivertti** [Cartopol/STS_Community_Warlord_Mod#14]
When having Ambush in your starting hand and not discarding Ambush the game played the card but crashed right after that. Here is the log:

Even discarding the card crashes the game. 

21:17:05.729 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at basemod.patches.com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.SafeDamageAllEnemies.checkSafety(SafeDamageAllEnemies.java:22) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.update(DamageAllEnemiesAction.java:52) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2512) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:879) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:427) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Comment by Cartopol** [comment]
Ambush has been changed, and no longer has this problem.
