### ISSUE TITLE
Skill Swap crashed the game

### ISSUE THREAD

**Issue by Vurttivertti** [Cartopol/STS_Community_Warlord_Mod#20]
Against Act 2 boss Collector. Had like 7 Tension when used Skill Swap and this happened.

23:32:28.117 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at the_warlord.actions.TensionToStrengthAction.update(TensionToStrengthAction.java:25) ~[WarlordMod.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2512) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:879) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:427) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

And the game crashed.

**Comment by Cartopol** [comment]
Solved in v0.0.6
